plugins {
    id 'com.gtnewhorizons.gtnhconvention'
    id 'com.diffplug.spotless' version '8.6.0'
}

spotless {
    enforceCheck false

    java {
        def packagePath = project.property('modGroup').toString().replace('.', '/')
        target fileTree('src') {
            include "*/java/${packagePath}/**/*.java"
        }

        leadingTabsToSpaces()
        endWithNewline()
        removeUnusedImports()
    }
}
